services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - ./static:/static:ro
      - ./media:/media:ro
    networks:
      - webnet
    restart: unless-stopped

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      DEFAULT_EMAIL: khitrov.aleksey@inbox.ru
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    networks:
      - webnet
    restart: unless-stopped

  nginx-static:
    image: nginx:alpine
    volumes:
      - ./static:/static:ro
      - ./nginx/static.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=shieldfire.ru
      - VIRTUAL_PATH=/static
    networks:
      - webnet
    restart: unless-stopped

  nginx-media:
    image: nginx:alpine
    volumes:
      - ./media:/media:ro
      - ./nginx/static.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=shieldfire.ru
      - VIRTUAL_PATH=/static
    networks:
      - webnet
    restart: unless-stopped

  web:
    image: aleks1832/djangoproject1-web:latest
    command: sh -c "python manage.py collectstatic --noinput && gunicorn djangoProject1.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    environment:
      - VIRTUAL_HOST=shieldfire.ru
      - LETSENCRYPT_HOST=shieldfire.ru
      - LETSENCRYPT_EMAIL=khitrov.aleksey@inbox.ru
    env_file:
      - .env
    networks:
      - webnet
    restart: unless-stopped

  celery:
    image: aleks1832/djangoproject1-web:latest
    command: celery -A djangoProject1 worker --loglevel=info --concurrency=2
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      replicas: 3
    depends_on:
      - redis
    networks:
      - webnet

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    networks:
      - webnet
    restart: unless-stopped

volumes:
  postgres_data:
  nginx_certs:
  nginx_html:

networks:
  webnet:
