# Generated by Django 5.1.2 on 2025-01-04 13:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Тип промокода')),
            ],
            options={
                'verbose_name': 'Тип промокода',
                'verbose_name_plural': 'Типы промокодов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Название промокода')),
                ('valid_from', models.DateTimeField(verbose_name='Начало действия промокода')),
                ('valid_to', models.DateTimeField(verbose_name='Конец действия промокода')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Выбрать размер скидки-%')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='Максимальное количество использований купона (0 - неограниченно)')),
                ('uses', models.PositiveIntegerField(default=0, editable=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.coupontype', verbose_name='Выбрать тип промокода')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['code'],
            },
        ),
    ]
