# Generated by Django 5.1.2 on 2024-11-14 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, max_length=11, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=50, verbose_name='Улица')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Дом/кор., кв./офис')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Почтовый код')),
                ('gender', models.CharField(blank=True, max_length=50, verbose_name='Пол')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Личный кабинет',
                'verbose_name_plural': 'Личный кабинет',
            },
        ),
    ]
