# Generated by Django 5.2.6 on 2025-09-11 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='Код подтверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, max_length=50, verbose_name='Пол')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('city', models.CharField(max_length=100, verbose_name='Город/населенный пункт')),
                ('street', models.CharField(max_length=100, verbose_name='Улица/Проспект')),
                ('house_number', models.CharField(max_length=100, verbose_name='Номер дома')),
                ('litter_number', models.CharField(blank=True, max_length=100, verbose_name='Корпус/литера/строение')),
                ('apartments_number', models.CharField(blank=True, max_length=100, verbose_name='Квартира/помещение')),
                ('floor', models.CharField(blank=True, max_length=100, verbose_name='Этаж')),
                ('elevator', models.BooleanField(blank=True, default=False, null=True, verbose_name='Наличие лифта')),
                ('intercom', models.BooleanField(blank=True, default=False, null=True, verbose_name='Наличие домофона')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='Почтовый код')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'unique_together': {('profile', 'country', 'region', 'city', 'street', 'house_number', 'litter_number', 'apartments_number', 'postal_code')},
            },
        ),
    ]
