# Generated by Django 5.1.2 on 2024-12-02 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Страна')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город/населенный пункт')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(blank=True, max_length=100, verbose_name='Номер дома')),
                ('litter_number', models.CharField(max_length=100, verbose_name='Корпус/литера/строение')),
                ('apartments_number', models.CharField(max_length=100, verbose_name='Квартира/помещение')),
                ('floor', models.CharField(max_length=100, verbose_name='Этаж')),
                ('elevator', models.CharField(max_length=100, verbose_name='Наличие лифта')),
                ('intercom', models.CharField(max_length=100, verbose_name='Наличие домофона')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='Почтовый код')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, max_length=11, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, max_length=50, verbose_name='Пол')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Личный кабинет',
                'verbose_name_plural': 'Личный кабинет',
            },
        ),
    ]
