# Generated by Django 5.1.2 on 2024-10-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='Номер телефона'),
        ),
    ]
