# Generated by Django 5.2a1 on 2025-06-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('paid', 'Оплачен'), ('completed', 'Выполненный'), ('canceled', 'Отмененный')], default='active', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
